### ISSUE TITLE
考虑过适配android13吗

### ISSUE THREAD

**Issue by ghost** [littleWhiteDuck/SimpleHook#12]
考虑过适配android13吗

**Comment by littleWhiteDuck** [comment]
计划中



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月5日(周四) 晚上6:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [littleWhiteDuck/SimpleHook] 考虑过适配android13吗 (Issue #12)




 
考虑过适配android13吗

**Comment by lycwhy1996** [comment]
现在需要手动复制新文件到软件data文件[尴尬]
