### ISSUE TITLE
请教能否hook字段 修改或打印

### ISSUE THREAD

**Issue by oncebeloved** [littleWhiteDuck/SimpleHook#15]
请教能否hook字段 修改或打印，怎么设置呢，给个示例吗？
![IMG_20230118_100520](https://user-images.githubusercontent.com/51181996/213063914-1ad0d3d0-9346-4ae6-9868-28523884b503.jpg)
![IMG_20230118_100618](https://user-images.githubusercontent.com/51181996/213063921-170d0d39-9abe-41a0-9b76-b8b613dbbb55.jpg)

**Comment by littleWhiteDuck** [comment]
请看readme，里面有介绍
