### ISSUE TITLE
1.2.8默认Android 10以上使用root将导致无root时无法使用

### ISSUE THREAD

**Issue by cxyzzz** [littleWhiteDuck/SimpleHook#17]
如题，1.2.7版本授予Android/data目录访问权限后可正常免root使用，升级1.2.8后无法使用，清除配置和模块数据也不行。如果只是data目录访问权限问题能否通过引入shizuku支持来支持无root运行？

**Comment by littleWhiteDuck** [comment]
android/data/有人用不了，我不清楚是什么原因，于是使用root权限将配置写到其他目录。
如果你使用lsp，是否授予相关作用域，以及本应用是否具有root权限，目标应用配置是否被打开。
如果以上都已做到，先清除lsp日志，然后强制停止运行目标应用，再打开目标应用，把lsp日志发过来。
至于shizuku我不清楚是否有用，在安卓13做过测试，android/data/目标应用包名/  下的文件 使用root权限写入文件也无法读取（所有者：root，需要更改所有者为相关目标应用才能正常读取）

**Comment by cxyzzz** [comment]
> android/data/有人用不了，我不清楚是什么原因，于是使用root权限将配置写到其他目录。 如果你使用lsp，是否授予相关作用域，以及本应用是否具有root权限，目标应用配置是否被打开。 如果以上都已做到，先清除lsp日志，然后强制停止运行目标应用，再打开目标应用，把lsp日志发过来。 至于shizuku我不清楚是否有用，在安卓13做过测试，android/data/目标应用包名/ 下的文件 使用root权限写入文件目标应用也无法读取（所有者：root，需要更改所有者为相关目标应用才能正常读取）

手机没有root，Android版本是12，用的lspatch运行的

**Comment by littleWhiteDuck** [comment]
下个版本会出一个lspatch版（使用NewXsp进行读写配置），仅会保留自定义hook功能。

**Comment by littleWhiteDuck** [comment]
好像lspatch并不支持 newxsp，此次更新并不能解决无root问题

**Comment by littleWhiteDuck** [comment]
[SimpleHook-1.2.9-23012422.zip](https://github.com/littleWhiteDuck/SimpleHook/files/10490944/SimpleHook-1.2.9-23012422.zip)

此版本可以内置配置，你可以通过MT管理器/NP管理器 打开apk，在assets内文件夹内找到configs文件，按照其内说明操作即可。

**Comment by cxyzzz** [comment]
不能同时实现1.2.7和1.2.8的方法吗？提供一个选项选择默认使用Android/data或者root权限写入配置，

**Comment by littleWhiteDuck** [comment]
存的地方不一样，hook的时候并不知道是哪个模式，需要读两次。用root一次到位，不需要考虑未来安卓14是否增强限制。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月25日(周三) 中午1:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [littleWhiteDuck/SimpleHook] 1.2.8默认Android 10以上使用root将导致无root时无法使用 (Issue #17)




 
不能同时实现1.2.7和1.2.8的方法吗？提供一个选项选择默认使用Android/data或者root权限写入配置，

**Comment by littleWhiteDuck** [comment]
> 不能同时实现1.2.7和1.2.8的方法吗？提供一个选项选择默认使用Android/data或者root权限写入配置，
[SimpleHook-normal-1.3.1_beta-23020621.zip](https://github.com/littleWhiteDuck/SimpleHook/files/10663480/SimpleHook-normal-1.3.1_beta-23020621.zip)
此为普通版，无需ROOT，由于是测试版，无法接收到更新提醒，请留意正式更新

**Comment by cxyzzz** [comment]
> > 不能同时实现1.2.7和1.2.8的方法吗？提供一个选项选择默认使用Android/data或者root权限写入配置，
> > [SimpleHook-normal-1.3.1_beta-23020621.zip](https://github.com/littleWhiteDuck/SimpleHook/files/10663480/SimpleHook-normal-1.3.1_beta-23020621.zip)
> > 此为普通版，无需ROOT，由于是测试版，无法接收到更新提醒，请留意正式更新

多谢作者，这个版本hook功能正常

**Comment by littleWhiteDuck** [comment]
[已发布正式版](https://github.com/littleWhiteDuck/SimpleHook/releases/tag/v1.3.1)
