### ISSUE TITLE
1.2.8hook返回值+报错

### ISSUE THREAD

**Issue by lckyd** [littleWhiteDuck/SimpleHook#18]
在LSPosed6713上使用simplehook1.2.8 hook返回值+ hook酷我音乐10.3.4.1时报错，但是该配置可以在simplehook1.2.7上正常工作
lsp日志：
[modules_2023-01-23.log](https://github.com/littleWhiteDuck/SimpleHook/files/10478443/modules_2023-01-23.log)
配置：{"appName":"酷我音乐","configs":"[{\"className\":\"cn.kuwo.base.bean.vipnew.MusicAuthInfo\",\"enable\":true,\"fieldClassName\":\"\",\"fieldName\":\"\",\"hookPoint\":\"after\",\"methodName\":\"getListenMusicAuthResult\",\"mode\":10,\"params\":\"cn.kuwo.service.DownloadProxy$Quality\",\"resultValues\":\"{\\\"albumBr\\\":0,\\\"albumId\\\":0,\\\"albumPrice\\\":-1.0,\\\"albumSt\\\":-1,\\\"hasPayAuthInfo\\\":true,\\\"mMusicChargeType\\\":\\\"SONG_VIP\\\",\\\"packType\\\":0,\\\"songBr\\\":20000,\\\"songFmt\\\":\\\"ZP\\\",\\\"songPid\\\":\\\"119616910\\\",\\\"songPrice\\\":2.0,\\\"songSt\\\":103,\\\"vipBr\\\":20000,\\\"vipCost\\\":0.0,\\\"vipFmt\\\":\\\"ZP\\\",\\\"vipPid\\\":\\\"119766782\\\",\\\"vipPrice\\\":0.0,\\\"vipSt\\\":102}\",\"returnClassName\":\"cn.kuwo.base.bean.vipnew.MusicAuthResult\"}]","description":"","enable":true,"id":5,"packageName":"cn.kuwo.player","versionName":"10.3.4.1"}

**Comment by littleWhiteDuck** [comment]
已修，等下个版本更新
