### ISSUE TITLE
return-void怎么填返回值

### ISSUE THREAD

**Issue by tozy1203** [littleWhiteDuck/SimpleHook#19]
在hook z方法时，返回值为return-void，试了nulls，empty都没用。
![Uploading Screenshot_2023-01-30-09-37-36-323_bin.mt.plus.jpg…]()

**Comment by littleWhiteDuck** [comment]
return void就是没有返回值



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月30日(周一) 上午9:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [littleWhiteDuck/SimpleHook] return-void怎么填返回值 (Issue #19)




 
在hook z方法时，返回值为return-void，试了nulls，empty都没用。
