### ISSUE TITLE
请求增加功能

### ISSUE THREAD

**Issue by wavetg** [littleWhiteDuck/SimpleHook#2]
在记录里面搜索MD5值时，增加从加密结果或者原始数据里搜索值，或者搜索选项增加完整匹配。而不是搜索全部数据。很多MD5值是多个值拼凑出来的，分析时出来太多的含有搜索值的结果，很难寻找完整匹配的结果。

**Comment by littleWhiteDuck** [comment]
下个版本会加入从加/解密结果、原始数据中搜索🔎



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月26日(周二) 上午6:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [littleWhiteDuck/SimpleHook] 请求增加功能 (Issue #2)




 
在记录里面搜索MD5值时，增加从加密结果或者原始数据里搜索值，或者搜索选项增加完整匹配。而不是搜索全部数据。很多MD5值是多个值拼凑出来的，分析时出来太多的含有搜索值的结果，很难寻找完整匹配的结果。

**Comment by littleWhiteDuck** [comment]
已更新 https://github.com/littleWhiteDuck/SimpleHook/releases
