### ISSUE TITLE
必须要存储权限吗？

### ISSUE THREAD

**Issue by superen7527** [littleWhiteDuck/SimpleHook#28]
有点奇怪 算法助手和这个都需要在data下获取权限写入配置，我想可能是因为防止目标应用没有存储权限所以不写入sd写到他们的私有目录。但是必须要存储文件吗，大部分这种应用hook类也没有这样的存储方式，直接设置好目标应用就可以hook了。实现方式上有什么不同吗？还是他们用的内存读取？

并不是对软件质疑，只是有点疑惑，能不能采用一种不需要读取data的方式实现？

**Comment by littleWhiteDuck** [comment]
使用lite版［仅支持LSP］不需要存储权限，但扩展功能会阉割，如果你不用扩展功能，那么没有任何影响。


像hook目标应用的算法，在打开软件的一瞬间可能有成千上万条信息，目前使用存储文件可能是最合适的，像使用广播会有延迟



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月13日(周五) 下午4:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [littleWhiteDuck/SimpleHook] 必须要存储权限吗？ (Issue #28)




 
有点奇怪 算法助手和这个都需要在data下获取权限写入配置，我想可能是因为防止目标应用没有存储权限所以不写入sd写到他们的私有目录。但是必须要存储文件吗，大部分这种应用hook类也没有这样的存储方式，直接设置好目标应用就可以hook了。实现方式上有什么不同吗？还是他们用的内存读取？
 
并不是对软件质疑，只是有点疑惑，能不能采用一种不需要读取data的方式实现？

**Comment by superen7527** [comment]
我说的就是扩展功能。


原来如此，是不是可以这样理解：
实际上是可以实现不采用存储文件的方式来实现扩展功能(就像传统模块的hook方式)，但会有读取性能损耗和反应上的延迟。相比之下存储文件的方式性能更好。

所以项目用的读写文件的方式，这样的理解有没有问题？


如果没理解错的话，那么想问一下在以后有空闲时，会不会出一个版本：支持不用存储权限来实现现在的扩展功能这样的包？

**Comment by littleWhiteDuck** [comment]
未来可能不需要任何权限，借助于LSP的新API



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月13日(周五) 下午4:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [littleWhiteDuck/SimpleHook] 必须要存储权限吗？ (Issue #28)




 
我说的就是扩展功能。
 
原来如此，是不是可以这样理解：
 实际上是可以实现不采用存储文件的方式来实现扩展功能(就像传统模块的hook方式)，但会有读取性能损耗和反应上的延迟。相比之下存储文件的方式性能更好。
 
所以项目用的读写文件的方式，这样的理解有没有问题？
 
如果没理解错的话，那么想问一下在以后有空闲时，会不会出一个版本：支持不用存储权限来实现现在的扩展功能这样的包？

**Comment by superen7527** [comment]
好的，也就是没有打算再做不依赖于存储文件方式的包。只可能等lsp新的api出现后才有会合并目前的三个版本为新的包。

感谢解答。
