### ISSUE TITLE
Hook参数或者返回值时，参数或者返回值为String类型，如果写入的是数字，默认会认定为int类型，会导致无法转换类型

### ISSUE THREAD

**Issue by laojichao** [littleWhiteDuck/SimpleHook#37]
![Screenshot_20240714_010205_SimpleHook.jpg](https://github.com/user-attachments/assets/17d1fbfc-b971-40a2-afa2-12d24337e948)

**Comment by Macrohard-X** [comment]
要写成`9999s`
