### ISSUE TITLE
hook实例变量失败

### ISSUE THREAD

**Issue by hdyyds666** [littleWhiteDuck/SimpleHook#4]
我hook了一个实例变量，但是没有效果
但是复制这个hook,改成记录实例变量，却可以记录 ，hook点before和after都不行，

app有储存权限，也能hook返回值，

**Comment by littleWhiteDuck** [comment]
变量可能在hook后被更改了，你要找准hook点



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月11日(周六) 下午3:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [littleWhiteDuck/SimpleHook] hook实例变量失败 (Issue #4)




 
我hook了一个实例变量，但是没有效果
 但是复制这个hook,改成记录实例变量，却可以记录 ，hook点before和after都不行，
 
app有储存权限，也能hook返回值，
