### ISSUE TITLE
可以不可以增加隐藏后台卡片的功能啊，

### ISSUE THREAD

**Issue by 9674454** [littleWhiteDuck/SimpleHook#8]
有时候手太快，看见就直接划掉后台卡片了，然后又得重新挂后台，配置才能生效

**Comment by littleWhiteDuck** [comment]
开启这个（见附图），并不需要挂后台

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月20日(周二) 凌晨4:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [littleWhiteDuck/SimpleHook] 可以不可以增加隐藏后台卡片的功能啊， (Issue #8)




 
有时候手太快，看见就直接划掉后台卡片了，然后又得重新挂后台，配置才能生效
